version: "3.7"
services:
  rss-api-backend:
    container_name: music-theory-backend
    image: treaudde/simple-development-environment:latest
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf


